twitter:
    consumer_key : 'CONSUMER_KEY'
    consumer_secret : 'CONSUMER_SECRET'
    token : 'TOKEN'
    token_secret : 'TOKEN_SECRET'

pgsql:
    dbname : 'DBNAME'
    user : 'USER'
    host : 'HOST'
    password : 'PASSWORD'
    
